name: Generate UML Diagrams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pyreverse
        run: |
          mkdir -p diagrams
          pyreverse -Smn -o png -p canvas ./core/src/toga/widgets/canvas
          pyreverse -ASmn -o png -p windows ./winforms/src/toga_winforms/widgets/canvas.py
          pyreverse -Smn -o png -p examples ./examples/canvas/canvas
          mv classes_canvas.png diagrams/
          mv classes_windows.png diagrams/
          mv classes_examples.png diagrams/

      - name: Upload UML Diagrams as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uml-diagrams
          path: diagrams/*.png

      - name: Display UML Diagrams in Summary
        run: |
          echo "## UML Diagrams" >> $GITHUB_STEP_SUMMARY
          echo "### Canvas UML" >> $GITHUB_STEP_SUMMARY
          echo "![Image](diagrams/classes_canvas.png)" >> $GITHUB_STEP_SUMMARY
          echo "### Windows UML" >> $GITHUB_STEP_SUMMARY
          echo "![Image](diagrams/classes_windows.png)" >> $GITHUB_STEP_SUMMARY
          echo "### Examples UML" >> $GITHUB_STEP_SUMMARY
          echo "![Image](diagrams/classes_examples.png)" >> $GITHUB_STEP_SUMMARY
